services:

  django:
    image: aulas2024tp:0.1
    build:
      context: ./backend/config/django-image
    volumes:
      - ./backend:/usr/app:delegated
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
    ports:
      - 8000:8000
    networks:
      red:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    ports:
      - ${DATABASE_PORT}:5432

  admin:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal:5432
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      red:
    
networks:
  red: