version: '3'

services:

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
    ports:
      - ${DATABASE_PORT}:5432

  admin:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal:5432
    depends_on:
      - db
    ports:
      - 8080:8080