# Generated by Django 5.0.6 on 2024-07-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_reservaaula_horariomateria'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='email',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
