# Generated by Django 5.0.6 on 2024-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0003_profesor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
