# Generated by Django 5.0.6 on 2024-07-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_alter_profesor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.CharField(blank=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
