# Generated by Django 5.0.6 on 2024-07-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0005_alter_profesor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='mostrar',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
